
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - /home/rui/uni/3ano2sem/WEB/EngWeb2024/Teste/contratos2024.csv:/datasets/dataset.json
    command: mongoimport --host mongodb -d contratos-db -c contratos --type json --file /datasets/dataset.json --jsonArray
